### ISSUE TITLE
Python 3.6.2 - Missing parentheses in call to 'print' 

### ISSUE THREAD

**Issue by DandiestSquare1** [BitMEX/easy-data-scripts#1]
get error using Python 3.6.2 on Win 10

**command that produced error:**
`C:\python\BitMEX-easy-data-scripts>python fetchExecutionTradeHistory.py -h`

**error:**
```Traceback (most recent call last):
  File "fetchExecutionTradeHistory.py", line 5, in <module>
    from lib import bitmex
  File "C:\python\BitMEX-easy-data-scripts\lib\bitmex.py", line 57
    print "Instrument not found: %s." % self.symbol
                                    ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by darkeclipz** [comment]
Replace it with:

`print("Instrument not found: %s." % self.symbol)`

Python 3 uses `print("hi")`, and Python 2 just `print "hi"`.

**Comment by bobpatchika** [comment]
what's the problem 
python ./facebook.py
python: can't open file './facebook.py': [Errno 2] No such file or directory

**Comment by ghost** [comment]
sorry I’m new to Python and github
Cencell
