### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by snodnipper** [BitMEX/easy-data-scripts#11]
Having updated `settings.py` (API_KEY / API_SECRET) and executing the following I get an error message.

```shell
python fetchExecutionTradeHistory.py --apiKey mykey --apiSecret my-api-secret
Traceback (most recent call last):
  File "fetchExecutionTradeHistory.py", line 60, in <module>
    keys = out[0].keys()
IndexError: list index out of range
```

I mounted this repo using:
```shell
docker run -it -v $(pwd):/root/code python:3.5-jessie /bin/bash
```

The API key and secret are valid.

**Comment by STRML** [comment]
This happens if no history is found. In recent weeks the range of historical queries has been greatly extended, so this should not happen in the usual case. In 4505f08, we print a sensible error if no data is found.

**Comment by Nimarrakers** [comment]
> Having updated `settings.py` (API_KEY / API_SECRET) and executing the following I get an error message.
> 
> ```shell
> python fetchExecutionTradeHistory.py --apiKey mykey --apiSecret my-api-secret
> Traceback (most recent call last):
>   File "fetchExecutionTradeHistory.py", line 60, in <module>
>     keys = out[0].keys()
> IndexError: list index out of range
> ```
> 
> I mounted this repo using:
> 
> ```shell
> docker run -it -v $(pwd):/root/code python:3.5-jessie /bin/bash
> ```
> 
> The API key and secret are valid.

**Comment by Nimarrakers** [comment]
> Having updated `settings.py` (API_KEY / API_SECRET) and executing the following I get an error message.
> 
> ```shell
> python fetchExecutionTradeHistory.py --apiKey mykey --apiSecret my-api-secret
> Traceback (most recent call last):
>   File "fetchExecutionTradeHistory.py", line 60, in <module>
>     keys = out[0].keys()
> IndexError: list index out of range
> ```
> 
> I mounted this repo using:
> 
> ```shell
> docker run -it -v $(pwd):/root/code python:3.5-jessie /bin/bash
> ```
> 
> The API key and secret are valid.

**Comment by Nimarrakers** [comment]
> Having updated `settings.py` (API_KEY / API_SECRET) and executing the following I get an error message.
> 
> ```shell
> python fetchExecutionTradeHistory.py --apiKey mykey --apiSecret my-api-secret
> Traceback (most recent call last):
>   File "fetchExecutionTradeHistory.py", line 60, in <module>
>     keys = out[0].keys()
> IndexError: list index out of range
> ```
> 
> I mounted this repo using:
> 
> ```shell
> docker run -it -v $(pwd):/root/code python:3.5-jessie /bin/bash
> ```
> 
> The API key and secret are valid.
