### ISSUE TITLE
Python 3 - SyntaxError bitmex.py

### ISSUE THREAD

**Issue by DandiestSquare1** [BitMEX/easy-data-scripts#3]
get error using Python 3.6.2 on Win 10

**command that produced error:**
`python fetchExecutionTradeHistory.py -h`

**error:**
```Traceback (most recent call last):
  File "fetchExecutionTradeHistory.py", line 5, in <module>
    from lib import bitmex
  File "C:\python\BitMEX-easy-data-scripts\lib\bitmex.py", line 203
    except requests.exceptions.HTTPError, e:
                                        ^
SyntaxError: invalid syntax
```

**Comment by STRML** [comment]
This isn't intended for py3 compatibility, please run using py2.

**Comment by DandiestSquare1** [comment]
In order to import using Python 3, I had to make a couple of changes:
- Lines 1, etc. of bitmex.py, change `from accessTokenAuth import *` to `from .accessTokenAuth import *`
- Lines 203, etc. of bitmex.py, change `except requests.exceptions.HTTPError, e` to `except requests.exceptions.HTTPError as e`
- add parentheses around the print function argument.
