### ISSUE TITLE
Trying to retreive trades real time

### ISSUE THREAD

**Issue by klaasv12** [BitMEX/easy-data-scripts#5]
Hi guys,

I am trying to retreive all the trades real time. However for whatever reason the feed does not seem to be updating anymore after running the first time. Does anyone have any idea what I can do to fix this?

`
import argparse
import json
import time
import csv
import sys
import datetime
from lib import bitmex
from settings import API_KEY, API_SECRET, API_BASE

parser = argparse.ArgumentParser(description='Fetch your full execution trade history from BitMEX.')
parser.add_argument('--apiKey', type=str, required=(not API_KEY), default=API_KEY,
                    help='API Key. Generate from https://www.bitmex.com/app/apiKeys')
parser.add_argument('--apiSecret', type=str, required=(not API_SECRET), default=API_SECRET,
                    help='API Secret.')
parser.add_argument('--fileType', type=str, default='json',
                    help='Output file type. Must end be json or csv.')
parser.add_argument('--filter', type=str,
                    help='Query filter as JSON.')

args = parser.parse_args()

fileType = args.fileType
if fileType != 'json' and fileType != 'csv':
    raise Exception('Output file type must be json or csv! Given: %s' % fileType)

if not args.apiKey or not args.apiSecret:
    print('Please fill in API_KEY and API_SECRET in settings.py!\n' +
          'You can create an API key from https://www.bitmex.com/app/apiKeys')
    sys.exit(1)

if(args.filter):
    try:
        json.loads(args.filter)
    except ValueError as e:
        raise ValueError("Filter is not valid JSON! Make sure to single-quote the string.")

connector = bitmex.BitMEX(base_url=API_BASE, apiKey=args.apiKey, apiSecret=args.apiSecret)

count = 100 # max API will allow
today = datetime.date.today()
query = {
    'reverse': 'true',
    'start': 0,
    'startTime': today,
    'count': count,
    'filter': args.filter
}

out = []
firsttime = 0
z=0
timeback=0
tijd=0
while True:
    data = connector._curl_bitmex(path="execution/tradeHistory", verb="GET", query=query)
    out.extend(data)
    trades = json.dumps(out, sort_keys=True, indent=4, separators=(',', ': '))
    trades = json.loads(trades)
    number = len(trades)
    x=number-1
    tijd = str(trades[0]["transactTime"])
    if tijd!=timeback and firsttime!=0:
        side = str(trades[0]["side"])
        size = str(trades[0]["cumQty"])
        product = str(trades[0]["symbol"])
        tijd = str(trades[0]["transactTime"])
        text = str(side+'   '+size+'   '+product+'   '+tijd)
    while x>=0 and firsttime==0:
        side = str(trades[x]["side"])
        size = str(trades[x]["cumQty"])
        product = str(trades[x]["symbol"])
        tijd = str(trades[x]["transactTime"])
        timeback = tijd
        text = str(side+'   '+size+'   '+product+'   '+tijd)
        print (text)
        x=x-1
    firsttime = 1
    time.sleep(5)
sys.exit()`

**Comment by STRML** [comment]
That's your personal trade history at `execution/tradeHistory` (you probably want `/trade`), but please don't do it this way. Connect to the websocket and subscribe to `execution`. https://github.com/BitMEX/api-connectors/tree/master/official-ws/delta-server can do it for you. Polling BitMEX HTTP endpoints is an easy way to get banned, and the data will be much more stale than if you connected to the socket.
