### ISSUE TITLE
Get transaction history

### ISSUE THREAD

**Issue by geeklingo** [BitMEX/easy-data-scripts#9]
Can't see an option to retrieve this info: https://testnet.bitmex.com/app/wallet. On their WS API page they mention ws.transact(), i tried unsuccessfully to change the code to get the info.

![image](https://user-images.githubusercontent.com/36504208/46171430-d31c1d80-c2e3-11e8-8ad7-26ecd685d09c.png)

This info makes it a lot easier to calculate whether you are ahead or not.

**Comment by STRML** [comment]
See the endpoint described at https://www.bitmex.com/api/explorer/#!/User/User_getWalletHistory.
